### ISSUE TITLE
Parameter Content Schemas

### ISSUE THREAD

**Issue by ggpwnkthx** [commonism/aiopenapi3#163]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read [the docs](https://aiopenapi3.readthedocs.org) and still think this feature is missing

### Description

Current version requires parameters to have either have a schema target or described schema. See https://github.com/commonism/aiopenapi3/blob/55b200da7bb3c8b39ee2e71c5a15a25acef81962/aiopenapi3/openapi.py#L500-L504

This does not follow the secondary prescribed serialization strategy for parameters. See https://spec.openapis.org/oas/latest.html#fixed-fields-9

**Comment by commonism** [comment]
media type mappings for parameters is not implemented.

try 
```python
                    for parameter in op.parameters + obj.parameters:
                        if parameter.schema_:
                            if isinstance(parameter.schema_, ReferenceBase):
                                schema = parameter.schema_._target
                            else:
                                schema = parameter.schema_
                            name = schema._get_identity("I2", f"{path}.{m}.{parameter.name}")
                            byname[name] = schema
                        else:
                            for key, mediatype in parameter.content.items():
                                schema = mediatype.schema_
                                name = schema._get_identity("I2", f"{path}.{m}.{parameter.name}.{key}")
                                byname[name] = schema
```
to get over the None access. 

Encoding of the parameter won't work either.

If possible -requires some unused fields in the https://spec.openapis.org/oas/v3.1.0#mediaTypeObject and content type application/json- use a plugin to change the document, move the schema from the media type object to the parameter.

I'll investigate how to address this properly.
My current understanding is the content type has to be aligned with the request body content type, and you can have multiple parameters with different distinct content-type,media type object mappings.

If you want to get into this …
https://github.com/commonism/aiopenapi3/blob/55b200da7bb3c8b39ee2e71c5a15a25acef81962/aiopenapi3/v30/glue.py#L304
https://github.com/commonism/aiopenapi3/blob/55b200da7bb3c8b39ee2e71c5a15a25acef81962/aiopenapi3/v30/parameter.py#L45
https://github.com/commonism/aiopenapi3/blob/55b200da7bb3c8b39ee2e71c5a15a25acef81962/aiopenapi3/v30/glue.py#L335

Can you provide an example section of your description document featuring this?

**Comment by ggpwnkthx** [comment]
Yeah, the work around for this isn't unmanageable. It's just more gnarliness from the Microsoft Graph API:
```
{
  "paths": {
    ...
    "/deviceManagement/getRoleScopeTagsByIds(ids={ids})": {
      "description": "Provides operations to call the getRoleScopeTagsByIds method.",
      "get": {
        "tags": ["deviceManagement.Functions"],
        "summary": "Invoke function getRoleScopeTagsByIds",
        "operationId": "deviceManagement.getRoleScopeTagsByIds",
        "parameters": [
          {
            "name": "ids",
            "in": "path",
            "description": "Usage: ids={ids}",
            "required": true,
            "content": {
              "application/json": {
                "schema": { "type": "array", "items": { "type": "string" } }
              }
            }
          },
        }, ...
      ], ...
    }, ...
  }, ...
}
```

**Comment by commonism** [comment]
This is a valid parameter with media type and additional header specified as encoding.
The additional header can specify another header.

```yaml
  parameters:
    EmptyFormQuery:
      in: query
      name: empty
      required: true
      content:
        "application/json":
          schema:
            type: number
          encoding:
            "*":
              style: form
              explode: false
              headers:
                X-hrm:
                  description: hrm header
                  content:
                    "*":
                      schema:
                        type: string
                        format: date-time
                      encoding:
                        "application/x-www-form-urlencoded":
                          style: form
```

As yours can be remapped without loosing information, I'd go with it as a start.
Doing this properly won't be as easy/fast/…

When doing this as plugin - after Cull.
